---
# tasks file for ansible-shell-mac

- name: Create ~/.git if directory does not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.git"
    state: directory
    mode: 0700

- name: Ensure taps
  homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Ensure zsh fonts are installed
  homebrew_cask:
    name: font-hack-nerd-font
    state: present

- name: Ensure zsh dependencies are installed
  homebrew:
    name: "{{ item }}"
    state: installed
  loop:
    - zsh-autosuggestions
    - zsh-completions
    - zsh-syntax-highlighting

- name: clone oh-my-zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.git/.oh-my-zsh"
    version: master

# - name: clone powerline/fonts
#   ansible.builtin.git:
#     repo: "https://github.com/powerline/fonts"
#     dest: "{{ ansible_env.HOME }}/.git/powerline-fonts"

# - name: link SourceCodePro powerline fonts
#   ansible.builtin.file:
#     src: "{{ ansible_env.HOME }}/.git/powerline-fonts/{{ item }}"
#     path: "{{ ansible_env.HOME }}/Library/Fonts/{{ item }}"
#     state: link
#   loop:
#     - "SourceCodePro"

- name: .zshrc
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/ansible-shell-mac/files/.zshrc"
    path: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    owner: "{{ ansible_env.USER }}"
    mode: 0644
